### ISSUE TITLE
import MacroTools: @capture fails for type matching

### ISSUE THREAD

**Issue by bvdmitri** [FluxML/MacroTools.jl#152] opened 2020-11-18 15:28 UTC
When `import MacroTools: @capture` it is impossible to match expression type.

E.g:
```
import MacroTools: @capture

@capture(:(a), sym_) # Works OK
```

```
import MacroTools: @capture

@capture(:(a), sym_Symbol) # Fails with UndefVarError: MacroTools not defined
```

With `using MacroTools` everything works as expected, but `using` is not always possible due to scoping and naming issues.
While fixing the problem is easy, from a user perspective I wouldn't expect this simple example to fail.

**Edit:** There is a similar issue #30.

**Comment by fingolfin** [comment] 2021-12-28 01:11
This is really a duplicate of #30.

Note that you can also do `import MacroTools` to solve the issue; this is perhaps less problematic than `using MacroTools`.

**Comment by cstjean** [comment] 2021-12-28 01:18
Closing as duplicate. Now that I'm de facto maintaining, I'd be happy to find a fix to this issue, even if it's very minor...

**Closed by cstjean** 2021-12-28 01:18 UTC
