### ISSUE TITLE
`isdef()` seems to return true in any case

### ISSUE THREAD

**Issue by omlins** [FluxML/MacroTools.jl#172] opened 2021-12-22 12:02 UTC
```
help?> MacroTools.isdef
  Test for function definition expressions.

julia> MacroTools.isdef(:(f() = 3))
true

julia> MacroTools.isdef(:(f()))
true

julia> MacroTools.isdef(:ix)
true

```

**Comment by omlins** [comment] 2021-12-22 15:28
The function `isdef` is defined as follows (see [here](https://github.com/FluxML/MacroTools.jl/blob/master/src/utils.jl#L234)):
```julia
isdef(ex) = isshortdef(ex) || longdef1(ex) !== nothing
```
The problem is that `longdef1(ex) !== nothing` does not at all check if `ex` is a function: if `ex` is not matched as short function definitions within `longdef1`, it is returned unchanged (see [here](https://github.com/FluxML/MacroTools.jl/blob/master/src/utils.jl#L241-L250)).

In `MacroTools.splitdef`, the check if an expression is a function is done differently - and hopefully correctly - using `longdef1` (https://github.com/FluxML/MacroTools.jl/blob/master/src/utils.jl#L298-L300):
```julia
@capture(longdef1(fdef), function (fcall_ | fcall_) body_ end)
```
I do not quite follow what the or statement here (`(fcall_ | fcall_)`) is supposed to do though.

**Comment by fingolfin** [comment] 2021-12-27 22:22
Duplicate of issue #154 ?

**Closed** 2023-12-19 17:34 UTC
